spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  flyway:
    enabled: false

app:
  jwt:
    secret: ${JWT_SECRET}
    expiration: 604800000
  gemini:
    api-key: ${GEMINI_API_KEY}
    model: gemini-1.5-flash-latest